stages:
  - test

test-php71:
  stage: test
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - apk add --no-cache py-pip &&
      pip install docker-compose
  script:
    - docker-compose run guzzlehttp-middleware-php71 composer check

test-php72:
  stage: test
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - apk add --no-cache py-pip &&
      pip install docker-compose
  script:
    - docker-compose run guzzlehttp-middleware-php72 composer check
